version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: sporty-rabbitmq
    ports:
      - "5673:5672"     # AMQP port (not default outside port)
      - "15673:15672"   # Management UI port (not default outside port)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - sporty-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:

networks:
  sporty-network:
    driver: bridge
