spring:
  application:
    name: consumer

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration

  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Logging Configuration
logging:
  level:
    com.axel.sporty.consumer: INFO
    org.springframework.amqp: DEBUG
